
    <div class="row">

    
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url());

    echo $this->form()->openTag($form);
    echo $this->formInput($form->get('id'));
    ?> 
<div class="panel panel-primary">
    <div class="panel panel-default">
 <div class="col-md-12 panel-heading text-center">Ajouter une pizza</div>
 <div class="col-md-12 panel-body"><div class="col-md-3"></div><div class="col-md-6 text-center">
  <?php echo $this->formInput($form->get('nom')); ?>
    </div><div class="col-md-3"></div></div>
     <div class="col-md-12 panel-body"><div class="col-md-3"></div><div class="col-md-6 text-center">
  <?php echo $this->formSelect($form->get('base')); ?>
    </div><div class="col-md-3"></div></div>
    <div class="col-md-12 panel-body"><div class="col-md-3"></div><div class="col-md-6 text-center">
  <?php echo $this->formRow($form->get('fileupload')); ?>
    </div><div class="col-md-3"></div></div>
    <?php if (isset($urlimage)) {
        echo "<div class=\"col-md-12 panel-body\"><div class=\"col-md-3\"></div><div class=\"col-md-6 text-center\"><img src=\"../../img/img_pizzas/" . $urlimage ."\" width=\"150px\"></div><div class=\"col-md-3\"></div></div>";
    }
    
    ?>
    <div class="col-md-12 panel-body"><div class="col-md-3"></div><div class="col-md-6 text-center">
  <?php echo $this->formMultiCheckbox($form->get('ingredients')); ?>
    </div><div class="col-md-3"></div></div>
    <div class="col-md-12 panel-body"><div class="col-md-3"></div><div class="col-md-6 text-center">
  <?php echo $this->formLabel($form->get('pizofday')); ?>
        <label class="toggle">
            <?php echo $this->formCheckbox($form->get('pizofday')); ?>
            <span class="handle"></span>
        </label>
    </div><div class="col-md-3"></div></div>
     <div class="col-md-12 panel-body"><div class="col-md-3"></div><div class="col-md-6 text-center">
        <?php echo $this->formLabel($form->get('pizza_au_menu')); ?>
        <label class="toggle">
            <?php echo $this->formCheckbox($form->get('pizza_au_menu')); ?>
            <span class="handle"></span>
        </label>
    </div><div class="col-md-3"></div></div>
     <div class="col-md-12 panel-body"><div class="col-md-3"></div><div class="col-md-6 text-center">
  <div class="input-group">
  <span class="input-group-addon">€</span>
  <?php echo $this->formInput($form->get('prix')); ?>
</div>
    </div><div class="col-md-3"></div></div>
     <div class="col-md-12 panel-body"><div class="col-md-3"></div><div class="col-md-6 text-center">
  <?php echo $this->formSubmit($form->get('submit')); ?>
    </div><div class="col-md-3"></div></div>
</div>
        
        <?php echo $this->form()->closeTag(); ?>

</div>