<div id="article">
    <div id="products" class="row list-group">
    <?php $base2 = null; foreach ($listepizza_page as $pizza) : 
                
                $base= $this->escapeHtml($pizza->getBase()->getId()); 
                
                if($base != $base2 ) { echo "<div class=\"page-header col-xs-12 col-lg-12 text-center\"><h1>".$this->escapeHtml($pizza->getBase()->getNom())."</h1></div>"; } ?>
    
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="thumbnaildiv"><img src="<?php echo ROOT_PATH . "../img/img_pizzas/" . $this->escapeHtml($pizza->getUrl_img()); ?>" alt="<?php echo $this->escapeHtml($pizza->getNom());?>"></div>
      <div class="caption">
        <h3><?php echo $this->escapeHtml($pizza->getNom());?></h3>
        <p class="group inner list-group-item-text" id="ingredientslist">Les ingrédients : <?php foreach ($pizza->getIngredients() as $ingredient) : echo " ".$ingredient->getNom() . "-"; endforeach; ?></p>
        <p class="lead"><?php echo $this->escapeHtml($pizza->getPrix());?>€</p>
        <p><a class="btn btn-success" onclick="popup(<?php echo $this->escapeHtml($pizza->getId());?>)" href="#">Ajouter au panier</a></p>
      </div>
    </div>
  </div>

 <?php $base2 = $this->escapeHtml($pizza->getBase()->getId()); endforeach; ?>   
    

</div></div>