<div class="page-header text-center">
    <h1>Créer un compte Piz'aoli</h1>
</div>
<?php
  $form = $this->form;
      $form->prepare();
    $form->setAttribute('action', $this->url('register'));
    echo $this->form()->openTag($form);
?>
<form>
    <div class="form-group">
        <label for="inputEmail"><?php echo $this->formLabel($form->get('email')); ?></label>
        <?php echo $this->formInput($form->get('email')); ?>
    </div>
    <div class="form-group">
        <label for="inputPassword"><?php echo $this->formLabel($form->get('password')); ?></label>
        <?php echo $this->formInput($form->get('password')); ?>
    </div>
    
    <?php echo $this->formSubmit($form->get('submit2')); ?>
<?php
echo $this->form()->closeTag(); ?>

<div class="row text-center">
  Si vous avez déjà un compte : <a href="/connect">cliquez ici pour vous connecter</a>
</div>